---
title: "Sevde"
author: "Analysis"
date: "March 6, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library (rvest)
library (tidyverse)
```

### Get raw data from BKM web page !


```{r}
raw_html <- read_html("https://bkm.com.tr/secilen-aya-ait-sektorel-gelisim/?filter_year=2018&filter_month=12&List=Listele")
raw_html
```


```{r}

tables_list <- raw_html %>% html_table (fill=TRUE)

df_raw <- tables_list[[4]]

df_raw <- df_raw %>% slice (-(1:2))

colnames(df_raw) <- c("type", "txn_cc", "txn_dc", "tl_cc", "tl_dc")

card_df <- df_raw %>% filter(type !="TOPLAM") %>% mutate_at (vars(txn_cc:tl_dc), funs(gsub("\\.","",.))) %>% mutate_at(vars(txn_cc:tl_dc), funs(as.numeric(gsub(",","\\.",.)))) %>% tbl_df()
```
## Analysis Time !
### TOP 5 Credit Card Transaction!

```{r}
card_df %>% 
  arrange(desc(txn_cc)) %>%
  slice(1:5) %>%
  knitr::kable() 
```

### TOP 5 Unit Credit Card Transaction according to categories !

```{r} 
card_df %>% 
  mutate(tl_cc_unit = tl_cc * 1000000 / txn_cc) %>%
  arrange(desc(tl_cc_unit)) %>%
  slice(1:5) %>%
  knitr::kable() 
```

### Bar chart of txn_cc

```{r, fig.height=6, fig.width=7} 

  ggplot(card_df,aes(x=reorder(type,-(txn_cc)),y=txn_cc/10^6, fill=type)) + 
  geom_bar(stat="identity") + 
  theme_minimal() +
  theme(axis.text.x=element_text(angle=90, hjust = 1, vjust = 0.5, size=6) , legend.position="none") +
  labs(x="", y="Credit Card Transaction Count")
```

### Bar chart of credit card cost
```{r, fig.height=6, fig.width=7} 
  ggplot(card_df,aes(x=reorder(type,-(tl_cc)),y=tl_cc, fill=type)) + 
  geom_bar(stat="identity") + 
  theme_minimal() +
  theme(axis.text.x=element_text(angle=90, hjust = 1, vjust = 0.5, size=6) , legend.position="none") +
  labs(x="", y="Credit Card Cost Cost (tl)")
```

### Bar chart of tl_cc / txn_cc
```{r, fig.height=6, fig.width=7} 
  ggplot(card_df,aes(x=reorder(type,-(tl_cc)),y=tl_cc/txn_cc, fill=type)) + 
  geom_bar(stat="identity") + 
  theme_minimal() +
  theme(axis.text.x=element_text(angle=90, hjust = 1, vjust = 0.5, size=6) , legend.position="none") +
  labs(x="", y="Unit Credit Card Cost Count")
```

### Bar chart of txn_dc
```{r, fig.height=6, fig.width=7} 
  ggplot(card_df,aes(x=reorder(type,-(txn_dc)),y=txn_dc, fill=type)) + 
  geom_bar(stat="identity") + 
  theme_minimal() +
  theme(axis.text.x=element_text(angle=90, hjust = 1, vjust = 0.5, size=6) , legend.position="none") +
  labs(x="", y="Debit Card Transaction ")
```

### Bar chart of unit debit card transaction
```{r, fig.height=6, fig.width=7} 
  ggplot(card_df,aes(x=reorder(type,-(txn_dc/tl_dc)),y=txn_dc/tl_dc, fill=type)) + 
  geom_bar(stat="identity") + 
  theme_minimal() +
  theme(axis.text.x=element_text(angle=90, hjust = 1, vjust = 0.5, size=6) , legend.position="none") +
  labs(x="", y="Debit Card Unit Costs ")
```

### Bar chart of tl_dc
```{r, fig.height=6, fig.width=7} 
  ggplot(card_df,aes(x=reorder(type,-(tl_dc)),y=tl_dc, fill=type)) + 
  geom_bar(stat="identity") + 
  theme_minimal() +
  theme(axis.text.x=element_text(angle=90, hjust = 1, vjust = 0.5, size=6) , legend.position="none") +
  labs(x="", y="Debit Card Unit Costs ")
```

### Free Analysis

```{r, fig.height=6, fig.width=7} 
  
card_df %>% 
  filter(type %in% c("HAVAYOLLARI", "ARABA KIRALAMA"))


```
  