---
title: "sevde"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


##Lets's Star

```{r} 
cars <- readRDS("C:\\Users\\STUDENT\\Desktop\\car_data_aggregate.rds")
glimpse(cars)
```

```{r}
cars_total <-
cars %>% 
group_by(year,month, brand_name)%>%
summarise(total= sum(total_total)) %>%
  filter(brand_name != "TOPLAM:")

cars_total
```

```{r}
yearly_total <-
cars %>%
  group_by(year,brand_name) %>%
  summarise(total=sum(total_total)) %>%
  filter(brand_name != "TOPLAM:") %>%
  group_by(year) %>%
  arrange(desc(total)) %>%
  slice(1)

ggplot(yearly_total,aes(x=year,y=total)) + geom_bar(stat="identity",aes(fill=brand_name))
  
```


```{r}
cars %>%
  group_by(month,brand_name) %>%
  summarise(total=sum(total_total)) %>%
  filter(month==1) %>%
  arrange(desc(total)) %>%
  filter(brand_name != "TOPLAM:") %>%
  slice(1:3)
  
cars %>%
  group_by(month,brand_name) %>%
  summarise(total=sum(total_total)) %>%
  filter(month==2) %>%
  arrange(desc(total)) %>%
  filter(brand_name != "TOPLAM:") %>%
  slice(1:3)

```